/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check
         * @description Liveness and dependency check. Returns 200 with `status: ok` when the database is reachable, `degraded` otherwise. The Redis check is included but does not affect the overall status because the cache falls back gracefully to the database on Redis errors.
         */
        get: operations["health_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List subjects
         * @description List monitored subjects with optional filters and pagination. Sorted by `last_synced_at` descending. Cached for `CACHE_LIST_TTL_SECONDS` (default 60s).
         */
        get: operations["list_subjects_v1_subjects_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a single subject
         * @description Fetch a single subject by its system-generated UUID.
         */
        get: operations["get_subject_v1_subjects__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get activity time-series for a subject
         * @description Return historical activity snapshots for a subject, newest first. Optional `from` and `to` ISO 8601 timestamps bound the time range. Capped at `limit` rows (default 1000, max 10000).
         */
        get: operations["get_activity_v1_subjects__subject_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Trigger on-demand sync for a subject
         * @description Enqueue a background task to sync data for this subject.
         */
        post: operations["trigger_sync_v1_subjects__subject_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}/videos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List videos for a subject
         * @description Return tracked videos for a YouTube subject, newest first. Each video includes the latest observed metrics (views, likes, comments). Capped at `limit` rows (default 50, max 100).
         */
        get: operations["list_videos_v1_subjects__subject_id__videos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/subjects/{subject_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List alert rules for a subject
         * @description Return all alert rules for a subject, newest first. Supports `active_only` filter and pagination.
         */
        get: operations["list_alerts_v1_subjects__subject_id__alerts_get"];
        put?: never;
        /**
         * Create an alert rule for a subject
         * @description Create a new alert rule. Requires an internal API key.
         */
        post: operations["create_alert_v1_subjects__subject_id__alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/alerts/{rule_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update an alert rule
         * @description Update an existing alert rule. Requires an internal API key.
         */
        put: operations["update_alert_v1_alerts__rule_id__put"];
        post?: never;
        /**
         * Delete an alert rule
         * @description Delete an alert rule. Requires an internal API key.
         */
        delete: operations["delete_alert_v1_alerts__rule_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a new API key
         * @description Create a new API key. Returns the raw key exactly once in the response - the server only retains the hash. Requires the admin token in the `Authorization: Bearer <ADMIN_TOKEN>` header. This endpoint does not require or use a regular X-API-Key.
         */
        post: operations["create_api_key_v1_admin_keys_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * APIKeyTier
         * @description API key tier. Controls rate limits and (in Sprint 2) write access.
         * @enum {string}
         */
        APIKeyTier: "internal" | "external_default" | "external_elevated";
        /**
         * ActivitySnapshot
         * @description Point-in-time metrics for a subject, stored as a time-series row.
         *
         *     Appended to the time-series store on every successful sync. Used by
         *     the Mini App for trend charts.
         */
        ActivitySnapshot: {
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Captured At
             * Format: date-time
             */
            captured_at: string;
            /** Followers */
            followers: number;
            /** Post Count */
            post_count: number;
            /** Frequency */
            frequency: number;
        };
        /**
         * AlertLog
         * @description Record of a single alert firing event.
         */
        AlertLog: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /**
             * Rule Id
             * Format: uuid
             */
            rule_id?: string | null;
            rule_type: components["schemas"]["AlertRuleType"];
            /**
             * Triggered At
             * Format: date-time
             */
            triggered_at: string;
            /** Metric Value */
            metric_value?: number | null;
            /** Threshold */
            threshold: number;
            /** Message */
            message: string;
            /** Delivered */
            delivered: boolean;
        };
        /**
         * AlertRule
         * @description Configurable alert condition scoped to one subject.
         *
         *     Created and updated by analysts through the Mini App; evaluated by
         *     the alert engine on each sync cycle. Phase 1 defines the contract
         *     and table; the engine itself ships in Phase 4.
         */
        AlertRule: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            rule_type: components["schemas"]["AlertRuleType"];
            /** Threshold */
            threshold: number;
            /** Cooldown Seconds */
            cooldown_seconds: number;
            /** Channel Id */
            channel_id: string;
            /**
             * Is Active
             * @default true
             */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at?: string;
        };
        /** AlertRuleCreate */
        AlertRuleCreate: {
            rule_type: components["schemas"]["AlertRuleType"];
            /** Threshold */
            threshold: number;
            /**
             * Cooldown Seconds
             * @default 3600
             */
            cooldown_seconds: number;
            /**
             * Channel Id
             * @default @default
             */
            channel_id: string;
        };
        /**
         * AlertRuleType
         * @description Type of alert condition evaluated by the alert engine.
         * @enum {string}
         */
        AlertRuleType: "follower_spike" | "follower_drop" | "activity_spike" | "activity_silence" | "status_change";
        /** AlertRuleUpdate */
        AlertRuleUpdate: {
            rule_type?: components["schemas"]["AlertRuleType"] | null;
            /** Threshold */
            threshold?: number | null;
            /** Cooldown Seconds */
            cooldown_seconds?: number | null;
            /** Channel Id */
            channel_id?: string | null;
            /** Is Active */
            is_active?: boolean | null;
        };
        /**
         * CreateKeyData
         * @description Response body for a newly-created API key.
         *
         *     The `api_key` field is the only place the raw key will ever appear.
         *     Save it immediately - the server cannot recover it later.
         */
        CreateKeyData: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            tier: components["schemas"]["APIKeyTier"];
            /** Key Prefix */
            key_prefix: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Api Key */
            api_key: string;
        };
        /**
         * CreateKeyRequest
         * @description Request body for creating a new API key.
         */
        CreateKeyRequest: {
            /**
             * Name
             * @description Human-readable label for the key (e.g. 'Mini App Prod').
             */
            name: string;
            /** @description Tier: `internal`, `external_default`, or `external_elevated`. */
            tier: components["schemas"]["APIKeyTier"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * Platform
         * @description Source platform for a subject. Extensible to new platforms (e.g. tiktok).
         * @enum {string}
         */
        Platform: "facebook" | "youtube" | "tiktok";
        /** ResponseEnvelope[AlertRule] */
        ResponseEnvelope_AlertRule_: {
            data: components["schemas"]["AlertRule"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[CreateKeyData] */
        ResponseEnvelope_CreateKeyData_: {
            data: components["schemas"]["CreateKeyData"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[Subject] */
        ResponseEnvelope_Subject_: {
            data: components["schemas"]["Subject"];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[ActivitySnapshot]] */
        ResponseEnvelope_list_ActivitySnapshot__: {
            /** Data */
            data: components["schemas"]["ActivitySnapshot"][];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[AlertLog]] */
        ResponseEnvelope_list_AlertLog__: {
            /** Data */
            data: components["schemas"]["AlertLog"][];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[AlertRule]] */
        ResponseEnvelope_list_AlertRule__: {
            /** Data */
            data: components["schemas"]["AlertRule"][];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[Subject]] */
        ResponseEnvelope_list_Subject__: {
            /** Data */
            data: components["schemas"]["Subject"][];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /** ResponseEnvelope[list[Video]] */
        ResponseEnvelope_list_Video__: {
            /** Data */
            data: components["schemas"]["Video"][];
            meta?: components["schemas"]["ResponseMeta"];
        };
        /**
         * ResponseMeta
         * @description Standard response metadata.
         *
         *     Always present in success responses. Fields are optional so the
         *     same shape works for single-resource and paginated list responses.
         */
        ResponseMeta: {
            /** Page */
            page?: number | null;
            /** Limit */
            limit?: number | null;
            /** Total */
            total?: number | null;
            /** Request Id */
            request_id?: string | null;
        };
        /**
         * Subject
         * @description Current state of a monitored subject.
         *
         *     Written by the collector, read by the API gateway. The `id` is a
         *     system-generated UUID; `platform_id` is the native identifier on
         *     the source platform (Facebook Page ID, YouTube Channel ID).
         */
        Subject: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            platform: components["schemas"]["Platform"];
            /** Platform Id */
            platform_id: string;
            /** Name */
            name: string;
            /** Display Name */
            display_name: string;
            /** Followers */
            followers: number;
            /** Post Count */
            post_count: number;
            /** Activity Frequency */
            activity_frequency: number;
            status: components["schemas"]["SubjectStatus"];
            /**
             * Last Synced At
             * Format: date-time
             */
            last_synced_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
            /** Extended Data */
            extended_data?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * SubjectStatus
         * @description Lifecycle status of a subject as observed by the collector.
         * @enum {string}
         */
        SubjectStatus: "active" | "inactive" | "suspended";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * Video
         * @description Per-video data for a YouTube subject.
         *
         *     Upserted on every sync cycle. Stores the latest observed metrics for
         *     each video; historical tracking is not maintained.
         */
        Video: {
            /**
             * Id
             * Format: uuid
             */
            id?: string;
            /**
             * Subject Id
             * Format: uuid
             */
            subject_id: string;
            /** Platform Video Id */
            platform_video_id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Thumbnail Url */
            thumbnail_url?: string | null;
            /**
             * Published At
             * Format: date-time
             */
            published_at: string;
            /** Duration */
            duration?: string | null;
            /**
             * View Count
             * @default 0
             */
            view_count: number;
            /**
             * Like Count
             * @default 0
             */
            like_count: number;
            /**
             * Comment Count
             * @default 0
             */
            comment_count: number;
            /**
             * Last Synced At
             * Format: date-time
             */
            last_synced_at: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    list_subjects_v1_subjects_get: {
        parameters: {
            query?: {
                /** @description Filter by platform: `facebook` or `youtube`. */
                platform?: components["schemas"]["Platform"] | null;
                /** @description Filter by status: `active`, `inactive`, or `suspended`. */
                status?: components["schemas"]["SubjectStatus"] | null;
                /** @description Case-insensitive search on name or platform_id. */
                q?: string | null;
                /** @description Include only subjects with `last_synced_at >=` this timestamp (ISO 8601). */
                last_synced_from?: string | null;
                /** @description Include only subjects with `last_synced_at <=` this timestamp (ISO 8601). */
                last_synced_to?: string | null;
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Items per page (max 100). */
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_Subject__"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid query parameters */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_subject_v1_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_Subject_"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_activity_v1_subjects__subject_id__activity_get: {
        parameters: {
            query?: {
                /** @description Lower bound on `captured_at` (ISO 8601). */
                from?: string | null;
                /** @description Upper bound on `captured_at` (ISO 8601). */
                to?: string | null;
                /** @description Max snapshots to return. */
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_ActivitySnapshot__"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID or timestamps */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    trigger_sync_v1_subjects__subject_id__sync_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_videos_v1_subjects__subject_id__videos_get: {
        parameters: {
            query?: {
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Items per page. */
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_Video__"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid UUID */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_alerts_v1_subjects__subject_id__alerts_get: {
        parameters: {
            query?: {
                /** @description Only return active rules. */
                active_only?: boolean;
                /** @description 1-indexed page number. */
                page?: number;
                /** @description Items per page (max 100). */
                limit?: number;
            };
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_list_AlertRule__"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_alert_v1_subjects__subject_id__alerts_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AlertRule_"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal API key required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Subject not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    update_alert_v1_alerts__rule_id__put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertRuleUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_AlertRule_"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal API key required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    delete_alert_v1_alerts__rule_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
                "X-API-Key"?: string | null;
            };
            path: {
                rule_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal API key required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rule not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Rate limit exceeded */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    create_api_key_v1_admin_keys_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateKeyRequest"];
            };
        };
        responses: {
            /** @description Key created. The `api_key` field in `data` is the raw key, shown once. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResponseEnvelope_CreateKeyData_"];
                };
            };
            /** @description Missing admin token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid admin token */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid request body */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
